version: "3"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:4.0-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379
    logging:
            driver: none
  app:
    build: .
    command: bash -c "rm -rf tmp/pids && bundle exec rails db:setup && bundle exec rails s -p 3000 -e development -b '0.0.0.0'"
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    ports:
      - "3000:3000"
    volumes:
      - tempdata:/usr/src/app/tmp
    links:
      - db
      - redis
    depends_on:
      db:
        condition: service_healthy
  sidekiq:
    build: .
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    volumes:
      - tempdata:/usr/src/app/tmp
    links:
      - db
      - redis
    depends_on:
      - app
      - redis
      - db
volumes:
  tempdata:
  redis:
  db:
